2024-10-06 20:58:21,496 INFO    StreamThr :7232 [internal.py:wandb_internal():85] W&B internal server running at pid: 7232, started at: 2024-10-06 20:58:21.495614
2024-10-06 20:58:21,496 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status
2024-10-06 20:58:21,497 INFO    WriterThread:7232 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/run-chpffej9.wandb
2024-10-06 20:58:21,499 DEBUG   SenderThread:7232 [sender.py:send():379] send: header
2024-10-06 20:58:21,499 DEBUG   SenderThread:7232 [sender.py:send():379] send: run
2024-10-06 20:58:22,484 INFO    SenderThread:7232 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files
2024-10-06 20:58:22,484 INFO    SenderThread:7232 [sender.py:_start_run_threads():1188] run started: chpffej9 with start time 1728266301.496175
2024-10-06 20:58:22,488 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 20:58:22,488 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: check_version
2024-10-06 20:58:22,581 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 20:58:22,588 DEBUG   HandlerThread:7232 [system_info.py:__init__():26] System info init
2024-10-06 20:58:22,588 DEBUG   HandlerThread:7232 [system_info.py:__init__():41] System info init done
2024-10-06 20:58:22,588 INFO    HandlerThread:7232 [system_monitor.py:start():194] Starting system monitor
2024-10-06 20:58:22,588 INFO    SystemMonitor:7232 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 20:58:22,588 INFO    HandlerThread:7232 [system_monitor.py:probe():214] Collecting system info
2024-10-06 20:58:22,589 INFO    SystemMonitor:7232 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 20:58:22,592 ERROR   HandlerThread:7232 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:22,593 INFO    SystemMonitor:7232 [interfaces.py:start():188] Started disk monitoring
2024-10-06 20:58:22,595 DEBUG   HandlerThread:7232 [system_info.py:probe():152] Probing system
2024-10-06 20:58:22,597 INFO    SystemMonitor:7232 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 20:58:22,597 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:22,598 INFO    SystemMonitor:7232 [interfaces.py:start():188] Started memory monitoring
2024-10-06 20:58:22,599 INFO    SystemMonitor:7232 [interfaces.py:start():188] Started network monitoring
2024-10-06 20:58:22,601 DEBUG   HandlerThread:7232 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 20:58:22,601 DEBUG   HandlerThread:7232 [system_info.py:probe():200] Probing system done
2024-10-06 20:58:22,601 DEBUG   HandlerThread:7232 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T01:58:22.597495', 'startedAt': '2024-10-07T01:58:21.489211', 'docker': None, 'cuda': None, 'args': ('data.pkl',), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/non_llm.py', 'codePathLocal': 'non_llm.py', 'codePath': 'non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 165.30055618286133}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 20:58:22,601 INFO    HandlerThread:7232 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 20:58:22,601 INFO    HandlerThread:7232 [system_monitor.py:probe():227] Publishing system info
2024-10-06 20:58:22,602 DEBUG   HandlerThread:7232 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 20:58:23,490 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/conda-environment.yaml
2024-10-06 20:58:24,602 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:24,652 DEBUG   HandlerThread:7232 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 20:58:24,652 INFO    HandlerThread:7232 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 20:58:24,654 DEBUG   SenderThread:7232 [sender.py:send():379] send: files
2024-10-06 20:58:24,654 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 20:58:24,883 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 20:58:24,883 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: python_packages
2024-10-06 20:58:24,883 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 20:58:24,884 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:24,884 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: stop_status
2024-10-06 20:58:24,893 INFO    wandb-upload_0:7232 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmpz2gnmu9bwandb/h16ndxae-wandb-metadata.json
2024-10-06 20:58:25,031 DEBUG   SenderThread:7232 [sender.py:send():379] send: telemetry
2024-10-06 20:58:25,495 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/conda-environment.yaml
2024-10-06 20:58:25,495 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/requirements.txt
2024-10-06 20:58:25,495 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-metadata.json
2024-10-06 20:58:25,495 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:25,927 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:26,612 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:26,926 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:27,477 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:27,503 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:27,930 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:28,639 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:28,934 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:29,939 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:30,655 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:30,947 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:31,950 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:32,666 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:32,909 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:32,953 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:33,964 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:34,678 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:34,959 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:35,970 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:36,685 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:36,975 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:37,940 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:37,999 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:38,704 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:39,020 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:39,889 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 20:58:39,898 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: stop_status
2024-10-06 20:58:40,010 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:40,752 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:41,023 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:42,030 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:42,765 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:43,040 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:43,062 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:44,092 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:44,777 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:45,081 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:46,069 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:46,787 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:47,074 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:47,599 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:48,083 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:48,562 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:48,793 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:49,079 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:49,297 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,299 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,299 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,299 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,299 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,300 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,300 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,300 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,300 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,301 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,301 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,301 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,301 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,302 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 20:58:49,303 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,303 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,303 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,303 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,303 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,303 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,303 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,304 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,304 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,304 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,304 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,305 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,305 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,305 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,305 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send():379] send: history
2024-10-06 20:58:49,305 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: summary_record
2024-10-06 20:58:49,306 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:49,604 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-summary.json
2024-10-06 20:58:50,084 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:50,806 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:51,089 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:51,615 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:52,094 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:52,814 ERROR   gpuapple  :7232 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 20:58:53,133 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:53,387 DEBUG   SenderThread:7232 [sender.py:send():379] send: telemetry
2024-10-06 20:58:53,388 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 20:58:53,388 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: server_info
2024-10-06 20:58:53,426 DEBUG   SenderThread:7232 [sender.py:send():379] send: exit
2024-10-06 20:58:53,426 INFO    SenderThread:7232 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 20:58:53,428 INFO    SenderThread:7232 [sender.py:send_exit():588] handling runtime: 30
2024-10-06 20:58:53,428 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:53,428 INFO    SenderThread:7232 [sender.py:send_exit():594] send defer
2024-10-06 20:58:53,428 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,429 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 20:58:53,429 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,429 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 20:58:53,429 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 1
2024-10-06 20:58:53,429 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,429 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 20:58:53,429 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,429 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 20:58:53,429 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 2
2024-10-06 20:58:53,429 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,429 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 20:58:53,429 INFO    HandlerThread:7232 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 20:58:53,429 DEBUG   SystemMonitor:7232 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 20:58:53,430 DEBUG   SystemMonitor:7232 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 20:58:53,430 INFO    HandlerThread:7232 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 20:58:53,430 DEBUG   SystemMonitor:7232 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 20:58:53,430 INFO    HandlerThread:7232 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 20:58:53,431 INFO    HandlerThread:7232 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 20:58:53,431 INFO    HandlerThread:7232 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 20:58:53,431 INFO    HandlerThread:7232 [interfaces.py:finish():200] Joined network monitor
2024-10-06 20:58:53,431 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,431 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 20:58:53,431 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 3
2024-10-06 20:58:53,431 DEBUG   SenderThread:7232 [sender.py:send():379] send: telemetry
2024-10-06 20:58:53,431 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,431 DEBUG   SenderThread:7232 [sender.py:send():379] send: stats
2024-10-06 20:58:53,431 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 20:58:53,432 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 4
2024-10-06 20:58:53,432 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,432 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 20:58:53,432 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 5
2024-10-06 20:58:53,432 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,432 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 20:58:53,432 DEBUG   SenderThread:7232 [sender.py:send():379] send: summary
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 20:58:53,432 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 20:58:53,432 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 6
2024-10-06 20:58:53,432 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,432 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 20:58:53,432 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,433 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 20:58:53,434 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 20:58:53,511 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 7
2024-10-06 20:58:53,511 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:53,511 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 20:58:53,511 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:53,511 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 20:58:53,621 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/config.yaml
2024-10-06 20:58:53,621 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-summary.json
2024-10-06 20:58:54,429 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 20:58:55,629 INFO    Thread-12 :7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:55,636 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 8
2024-10-06 20:58:55,636 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 20:58:55,636 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:55,638 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 20:58:55,638 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:55,638 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 20:58:55,639 INFO    SenderThread:7232 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 20:58:55,642 INFO    SenderThread:7232 [job_builder.py:_get_source_type():580] no source found
2024-10-06 20:58:55,642 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 9
2024-10-06 20:58:55,643 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:55,643 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 20:58:55,643 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:55,643 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 20:58:55,643 INFO    SenderThread:7232 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 20:58:56,441 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 20:58:56,632 INFO    SenderThread:7232 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:56,633 INFO    SenderThread:7232 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files
2024-10-06 20:58:56,633 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/requirements.txt requirements.txt
2024-10-06 20:58:56,633 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log output.log
2024-10-06 20:58:56,637 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/config.yaml config.yaml
2024-10-06 20:58:56,638 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-summary.json wandb-summary.json
2024-10-06 20:58:56,639 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/conda-environment.yaml conda-environment.yaml
2024-10-06 20:58:56,641 INFO    SenderThread:7232 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-metadata.json wandb-metadata.json
2024-10-06 20:58:56,641 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 10
2024-10-06 20:58:56,641 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 20:58:56,641 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:56,642 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 20:58:56,644 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:56,644 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 20:58:56,644 INFO    SenderThread:7232 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 20:58:56,871 INFO    wandb-upload_3:7232 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/wandb-summary.json
2024-10-06 20:58:56,872 INFO    wandb-upload_1:7232 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/output.log
2024-10-06 20:58:56,879 INFO    wandb-upload_4:7232 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/conda-environment.yaml
2024-10-06 20:58:56,982 INFO    wandb-upload_0:7232 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/requirements.txt
2024-10-06 20:58:56,982 INFO    wandb-upload_2:7232 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/files/config.yaml
2024-10-06 20:58:57,186 INFO    Thread-11 (_thread_body):7232 [sender.py:transition_state():614] send defer: 11
2024-10-06 20:58:57,186 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:57,186 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 20:58:57,187 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:57,187 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 20:58:57,187 INFO    SenderThread:7232 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 20:58:57,187 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 12
2024-10-06 20:58:57,188 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:57,188 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 20:58:57,188 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:57,188 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 20:58:57,188 INFO    SenderThread:7232 [file_stream.py:finish():601] file stream finish called
2024-10-06 20:58:57,293 INFO    SenderThread:7232 [file_stream.py:finish():605] file stream finish is done
2024-10-06 20:58:57,293 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 13
2024-10-06 20:58:57,293 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:57,293 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 20:58:57,294 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:57,294 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 20:58:57,294 INFO    SenderThread:7232 [sender.py:transition_state():614] send defer: 14
2024-10-06 20:58:57,295 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: defer
2024-10-06 20:58:57,295 DEBUG   SenderThread:7232 [sender.py:send():379] send: final
2024-10-06 20:58:57,295 INFO    HandlerThread:7232 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 20:58:57,295 DEBUG   SenderThread:7232 [sender.py:send():379] send: footer
2024-10-06 20:58:57,295 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: defer
2024-10-06 20:58:57,295 INFO    SenderThread:7232 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 20:58:57,297 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 20:58:57,297 DEBUG   SenderThread:7232 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 20:58:57,298 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 20:58:57,299 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 20:58:57,299 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 20:58:57,303 DEBUG   HandlerThread:7232 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 20:58:57,304 INFO    HandlerThread:7232 [handler.py:finish():882] shutting down handler
2024-10-06 20:58:58,302 INFO    WriterThread:7232 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_205821-chpffej9/run-chpffej9.wandb
2024-10-06 20:58:58,302 INFO    SenderThread:7232 [sender.py:finish():1608] shutting down sender
2024-10-06 20:58:58,303 INFO    SenderThread:7232 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 20:58:58,303 INFO    SenderThread:7232 [file_pusher.py:join():175] waiting for file pusher
