2024-10-06 22:47:25,615 INFO    StreamThr :9328 [internal.py:wandb_internal():85] W&B internal server running at pid: 9328, started at: 2024-10-06 22:47:25.614511
2024-10-06 22:47:25,616 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status
2024-10-06 22:47:25,617 INFO    WriterThread:9328 [datastore.py:open_for_write():87] open: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/run-296jnim4.wandb
2024-10-06 22:47:25,618 DEBUG   SenderThread:9328 [sender.py:send():379] send: header
2024-10-06 22:47:25,618 DEBUG   SenderThread:9328 [sender.py:send():379] send: run
2024-10-06 22:47:25,844 INFO    SenderThread:9328 [dir_watcher.py:__init__():211] watching files in: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files
2024-10-06 22:47:25,844 INFO    SenderThread:9328 [sender.py:_start_run_threads():1188] run started: 296jnim4 with start time 1728272845.614918
2024-10-06 22:47:25,850 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: check_version
2024-10-06 22:47:25,850 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: check_version
2024-10-06 22:47:25,915 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: run_start
2024-10-06 22:47:25,925 DEBUG   HandlerThread:9328 [system_info.py:__init__():26] System info init
2024-10-06 22:47:25,925 DEBUG   HandlerThread:9328 [system_info.py:__init__():41] System info init done
2024-10-06 22:47:25,925 INFO    HandlerThread:9328 [system_monitor.py:start():194] Starting system monitor
2024-10-06 22:47:25,925 INFO    SystemMonitor:9328 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-10-06 22:47:25,925 INFO    HandlerThread:9328 [system_monitor.py:probe():214] Collecting system info
2024-10-06 22:47:25,926 INFO    SystemMonitor:9328 [interfaces.py:start():188] Started cpu monitoring
2024-10-06 22:47:25,926 INFO    SystemMonitor:9328 [interfaces.py:start():188] Started disk monitoring
2024-10-06 22:47:25,930 INFO    SystemMonitor:9328 [interfaces.py:start():188] Started gpuapple monitoring
2024-10-06 22:47:25,931 ERROR   HandlerThread:9328 [gpu_apple.py:probe():176] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 164, in probe
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:25,932 INFO    SystemMonitor:9328 [interfaces.py:start():188] Started memory monitoring
2024-10-06 22:47:25,932 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:25,934 DEBUG   HandlerThread:9328 [system_info.py:probe():152] Probing system
2024-10-06 22:47:25,935 INFO    SystemMonitor:9328 [interfaces.py:start():188] Started network monitoring
2024-10-06 22:47:25,937 DEBUG   HandlerThread:9328 [gitlib.py:_init_repo():56] git repository is invalid
2024-10-06 22:47:25,937 DEBUG   HandlerThread:9328 [system_info.py:probe():200] Probing system done
2024-10-06 22:47:25,937 DEBUG   HandlerThread:9328 [system_monitor.py:probe():223] {'os': 'macOS-14.6.1-arm64-arm-64bit', 'python': '3.12.2', 'heartbeatAt': '2024-10-07T03:47:25.935249', 'startedAt': '2024-10-07T03:47:25.608647', 'docker': None, 'cuda': None, 'args': ('data.pkl', 'RF'), 'state': 'running', 'program': '/Users/milind/Desktop/valence/milind_code/train_non_llm.py', 'codePathLocal': 'train_non_llm.py', 'codePath': 'train_non_llm.py', 'host': 'Milinds-MacBook-Pro.local', 'username': 'milind', 'executable': '/opt/anaconda3/bin/python', 'cpu_count': 8, 'cpu_count_logical': 8, 'disk': {'/': {'total': 228.27386474609375, 'used': 167.2612190246582}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-10-06 22:47:25,937 INFO    HandlerThread:9328 [system_monitor.py:probe():224] Finished collecting system info
2024-10-06 22:47:25,937 INFO    HandlerThread:9328 [system_monitor.py:probe():227] Publishing system info
2024-10-06 22:47:25,937 DEBUG   HandlerThread:9328 [system_info.py:_save_conda():209] Saving list of conda packages installed into the current environment
2024-10-06 22:47:26,850 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/conda-environment.yaml
2024-10-06 22:47:27,941 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:28,031 DEBUG   HandlerThread:9328 [system_info.py:_save_conda():224] Saving conda packages done
2024-10-06 22:47:28,032 INFO    HandlerThread:9328 [system_monitor.py:probe():229] Finished publishing system info
2024-10-06 22:47:28,034 DEBUG   SenderThread:9328 [sender.py:send():379] send: files
2024-10-06 22:47:28,034 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-metadata.json with policy now
2024-10-06 22:47:28,247 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: python_packages
2024-10-06 22:47:28,247 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: python_packages
2024-10-06 22:47:28,247 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 22:47:28,247 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: stop_status
2024-10-06 22:47:28,247 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:28,309 INFO    wandb-upload_0:9328 [upload_job.py:push():130] Uploaded file /var/folders/jv/wvjkll0d0vl_clbchr37hpk40000gn/T/tmp0f3j5fbjwandb/3r39di4h-wandb-metadata.json
2024-10-06 22:47:28,392 DEBUG   SenderThread:9328 [sender.py:send():379] send: telemetry
2024-10-06 22:47:28,860 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/conda-environment.yaml
2024-10-06 22:47:28,861 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/output.log
2024-10-06 22:47:28,861 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/requirements.txt
2024-10-06 22:47:28,861 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-metadata.json
2024-10-06 22:47:29,253 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:29,950 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:30,258 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:30,866 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/output.log
2024-10-06 22:47:31,276 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:31,406 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 22:47:31,971 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:32,298 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:33,288 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:33,986 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:34,293 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:35,300 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:36,001 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:36,304 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:37,271 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 22:47:37,306 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:38,012 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:38,311 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:39,328 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:40,023 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:40,328 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:41,330 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:42,036 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:42,338 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:43,250 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: stop_status
2024-10-06 22:47:43,250 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: stop_status
2024-10-06 22:47:43,336 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:43,406 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 22:47:44,044 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:44,341 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:45,342 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:46,053 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:46,347 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:47,353 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:48,058 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:48,352 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:49,267 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 22:47:49,359 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:50,074 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:50,370 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:51,376 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:52,084 ERROR   gpuapple  :9328 [gpu_apple.py:sample():110] GPU stats error: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/internal/system/assets/gpu_apple.py", line 64, in sample
    subprocess.check_output(command, universal_newlines=True)
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/anaconda3/lib/python3.12/subprocess.py", line 1953, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/lib/python3.12/site-packages/wandb/bin/apple_gpu_stats'
2024-10-06 22:47:52,377 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:52,869 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,871 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,873 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,873 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,873 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,874 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,876 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,880 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,880 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,883 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,889 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,892 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,903 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,904 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,905 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,906 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:52,908 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,908 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,908 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,908 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,908 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,908 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,908 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,909 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,909 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,909 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,909 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,909 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,910 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,910 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,910 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,910 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:52,910 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:52,910 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:52,911 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:53,003 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-summary.json
2024-10-06 22:47:53,390 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:53,895 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: partial_history
2024-10-06 22:47:53,896 DEBUG   SenderThread:9328 [sender.py:send():379] send: history
2024-10-06 22:47:53,897 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: summary_record
2024-10-06 22:47:53,897 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:53,925 DEBUG   SenderThread:9328 [sender.py:send():379] send: telemetry
2024-10-06 22:47:53,929 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: server_info
2024-10-06 22:47:53,930 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: server_info
2024-10-06 22:47:53,972 DEBUG   SenderThread:9328 [sender.py:send():379] send: exit
2024-10-06 22:47:53,972 INFO    SenderThread:9328 [sender.py:send_exit():586] handling exit code: 0
2024-10-06 22:47:53,973 INFO    SenderThread:9328 [sender.py:send_exit():588] handling runtime: 28
2024-10-06 22:47:53,973 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:53,973 INFO    SenderThread:9328 [sender.py:send_exit():594] send defer
2024-10-06 22:47:53,974 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,974 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 0
2024-10-06 22:47:53,974 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,974 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 0
2024-10-06 22:47:53,975 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 1
2024-10-06 22:47:53,975 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,975 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 1
2024-10-06 22:47:53,975 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,975 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 1
2024-10-06 22:47:53,975 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 2
2024-10-06 22:47:53,975 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 2
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [system_monitor.py:finish():203] Stopping system monitor
2024-10-06 22:47:53,976 DEBUG   SystemMonitor:9328 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [interfaces.py:finish():200] Joined cpu monitor
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [interfaces.py:finish():200] Joined disk monitor
2024-10-06 22:47:53,976 DEBUG   SystemMonitor:9328 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [interfaces.py:finish():200] Joined gpuapple monitor
2024-10-06 22:47:53,976 DEBUG   SystemMonitor:9328 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-10-06 22:47:53,976 INFO    HandlerThread:9328 [interfaces.py:finish():200] Joined memory monitor
2024-10-06 22:47:53,977 INFO    HandlerThread:9328 [interfaces.py:finish():200] Joined network monitor
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 2
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 3
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send():379] send: telemetry
2024-10-06 22:47:53,978 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send():379] send: stats
2024-10-06 22:47:53,978 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 3
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 3
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 4
2024-10-06 22:47:53,978 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,978 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 4
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 4
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 5
2024-10-06 22:47:53,978 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,978 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 5
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send():379] send: summary
2024-10-06 22:47:53,978 INFO    SenderThread:9328 [sender.py:_save_file():1454] saving file wandb-summary.json with policy end
2024-10-06 22:47:53,978 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,979 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 5
2024-10-06 22:47:53,979 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 6
2024-10-06 22:47:53,979 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:53,979 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 6
2024-10-06 22:47:53,979 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:53,979 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 6
2024-10-06 22:47:53,980 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: status_report
2024-10-06 22:47:54,009 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-summary.json
2024-10-06 22:47:54,062 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 7
2024-10-06 22:47:54,062 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:54,062 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 7
2024-10-06 22:47:54,062 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:54,062 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 7
2024-10-06 22:47:54,451 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 8
2024-10-06 22:47:54,451 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:54,451 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 8
2024-10-06 22:47:54,451 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:54,452 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 8
2024-10-06 22:47:54,452 INFO    SenderThread:9328 [job_builder.py:build():440] Attempting to build job artifact
2024-10-06 22:47:54,453 INFO    SenderThread:9328 [job_builder.py:_get_source_type():580] no source found
2024-10-06 22:47:54,453 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 9
2024-10-06 22:47:54,453 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:54,453 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 9
2024-10-06 22:47:54,453 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:54,454 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 9
2024-10-06 22:47:54,454 INFO    SenderThread:9328 [dir_watcher.py:finish():358] shutting down directory watcher
2024-10-06 22:47:54,980 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 22:47:55,013 INFO    Thread-12 :9328 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/output.log
2024-10-06 22:47:55,015 INFO    SenderThread:9328 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/config.yaml
2024-10-06 22:47:55,015 INFO    SenderThread:9328 [dir_watcher.py:finish():388] scan: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files
2024-10-06 22:47:55,015 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/requirements.txt requirements.txt
2024-10-06 22:47:55,016 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/output.log output.log
2024-10-06 22:47:55,018 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/config.yaml config.yaml
2024-10-06 22:47:55,020 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-summary.json wandb-summary.json
2024-10-06 22:47:55,023 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/conda-environment.yaml conda-environment.yaml
2024-10-06 22:47:55,025 INFO    SenderThread:9328 [dir_watcher.py:finish():402] scan save: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-metadata.json wandb-metadata.json
2024-10-06 22:47:55,027 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 10
2024-10-06 22:47:55,027 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 22:47:55,027 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:55,027 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 10
2024-10-06 22:47:55,028 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:55,028 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 10
2024-10-06 22:47:55,028 INFO    SenderThread:9328 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 22:47:55,218 INFO    wandb-upload_0:9328 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/requirements.txt
2024-10-06 22:47:55,254 INFO    wandb-upload_4:9328 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/conda-environment.yaml
2024-10-06 22:47:55,255 INFO    wandb-upload_2:9328 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/config.yaml
2024-10-06 22:47:55,285 INFO    wandb-upload_1:9328 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/output.log
2024-10-06 22:47:55,318 INFO    wandb-upload_3:9328 [upload_job.py:push():130] Uploaded file /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/files/wandb-summary.json
2024-10-06 22:47:55,524 INFO    Thread-11 (_thread_body):9328 [sender.py:transition_state():614] send defer: 11
2024-10-06 22:47:55,524 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:55,524 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 11
2024-10-06 22:47:55,525 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:55,525 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 11
2024-10-06 22:47:55,525 INFO    SenderThread:9328 [file_pusher.py:join():175] waiting for file pusher
2024-10-06 22:47:55,526 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 12
2024-10-06 22:47:55,526 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:55,526 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 12
2024-10-06 22:47:55,526 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:55,526 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 12
2024-10-06 22:47:55,526 INFO    SenderThread:9328 [file_stream.py:finish():601] file stream finish called
2024-10-06 22:47:55,607 INFO    SenderThread:9328 [file_stream.py:finish():605] file stream finish is done
2024-10-06 22:47:55,608 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 13
2024-10-06 22:47:55,608 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:55,608 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 13
2024-10-06 22:47:55,609 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:55,609 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 13
2024-10-06 22:47:55,609 INFO    SenderThread:9328 [sender.py:transition_state():614] send defer: 14
2024-10-06 22:47:55,609 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: defer
2024-10-06 22:47:55,609 DEBUG   SenderThread:9328 [sender.py:send():379] send: final
2024-10-06 22:47:55,609 INFO    HandlerThread:9328 [handler.py:handle_request_defer():184] handle defer: 14
2024-10-06 22:47:55,609 DEBUG   SenderThread:9328 [sender.py:send():379] send: footer
2024-10-06 22:47:55,610 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: defer
2024-10-06 22:47:55,610 INFO    SenderThread:9328 [sender.py:send_request_defer():610] handle sender defer: 14
2024-10-06 22:47:55,611 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: poll_exit
2024-10-06 22:47:55,611 DEBUG   SenderThread:9328 [sender.py:send_request():406] send_request: poll_exit
2024-10-06 22:47:55,612 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: internal_messages
2024-10-06 22:47:55,613 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: get_summary
2024-10-06 22:47:55,613 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: sampled_history
2024-10-06 22:47:55,627 DEBUG   HandlerThread:9328 [handler.py:handle_request():158] handle_request: shutdown
2024-10-06 22:47:55,627 INFO    HandlerThread:9328 [handler.py:finish():882] shutting down handler
2024-10-06 22:47:56,612 INFO    SenderThread:9328 [sender.py:finish():1608] shutting down sender
2024-10-06 22:47:56,612 INFO    WriterThread:9328 [datastore.py:close():296] close: /Users/milind/Desktop/valence/milind_code/wandb/run-20241006_224725-296jnim4/run-296jnim4.wandb
2024-10-06 22:47:56,613 INFO    SenderThread:9328 [file_pusher.py:finish():169] shutting down file pusher
2024-10-06 22:47:56,613 INFO    SenderThread:9328 [file_pusher.py:join():175] waiting for file pusher
